# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c7592037e169073cd24f635fef85764d0ba042a5f29da5e78625dc08976f7e32de003acdf88557e2be1b968d98ae3d7ffb9e0ca6336dd298c5e5ad5c58e17b

test:
  secret_key_base: 0be9e9d3afdd163af1cca0bc0d20e3004bab9679afff9de2bacff2cad78869e0c610dca6965d62cc4fd4e89fb059633b3bcb0fa4358bb924f3e1e6c55774f276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
